services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # ESTO LO QUE HACE ES QUE LEA LAS DEPS DE DONDE ESTÁN
      - .:/app # ESTO MAPEA . A :/app EN EL CONTENEDOR
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: [ "npm", "run", "test" ]
